image:
  repository: codercom/code-server
  tag: '4.12.0'
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  hosts:
  - host: code.burrell.tech
    paths:
    - /
  tls:
  - secretName: code.burrell.tech
    hosts:
    - code.burrell.tech
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: 'unproxied.burrell.tech'
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
    nginx.ingress.kubernetes.io/auth-url: "http://code-server-oauth2-proxy.code-server.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
persistence:
  storageClass: nfs-rwo
  size: 50Gi
extraArgs:
- "--auth"
- "none"
extraVars:
- name: EXTENSIONS_GALLERY
  value: '{"serviceUrl":"https://marketplace.visualstudio.com/_apis/public/gallery","cacheUrl": "https://vscode.blob.core.windows.net/gallery/index","itemUrl": "https://marketplace.visualstudio.com/items"}'
