ingress:
  enabled: true
  hosts:
  - host: code.burrell.tech
    paths:
    - /
  tls:
  - secretName: code.burrell.tech
    hosts:
    - code.burrell.tech
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/target: 'burrell.tech'
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
    # nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    # nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
persistence:
  storageClass: nfs-rwo
  size: 50Gi
extraArgs:
- "--auth"
- "none"
