ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/target: 'burrell.tech'
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
  hosts:
  - code.burrell.tech
  path: /oauth2/
  tls:
  - secretName: code.burrell.tech
    hosts:
    - code.burrell.tech

config:
  existingSecret: auth0-secret
  cookieName: burrellCodeServer

extraEnv:
  OAUTH2_PROXY_PROVIDER: oidc
  OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: Auth0
  OAUTH2_PROXY_REDIRECT_URL: https://code.burrell.tech/oauth2/callback
  OAUTH2_PROXY_OIDC_ISSUER_URL: https://burrell.us.auth0.com/authorize
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
