ingress:
  enabled: true
  annotations:

    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: 'unproxied.burrell.tech'
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
  hosts:
  - code.burrell.tech
  path: /oauth2
  pathType: Prefix
  tls:
  - secretName: code.burrell.tech
    hosts:
    - code.burrell.tech

config:
  existingSecret: auth0-secret
  cookieName: burrellCodeServer

extraEnv:
- name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
  value: "true"
- name: OAUTH2_PROXY_PROVIDER
  value: oidc
- name: OAUTH2_PROXY_PROVIDER_DISPLAY_NAME
  value: Auth0
- name: OAUTH2_PROXY_REDIRECT_URL
  value: https://code.burrell.tech/oauth2/callback
- name: OAUTH2_PROXY_OIDC_ISSUER_URL
  value: https://burrell.us.auth0.com/
- name: OAUTH2_PROXY_LOGIN_URL
  value: https://burrell.us.auth0.com/authorize
- name: OAUTH2_PROXY_OIDC_JWKS_URL
  value: "https://burrell.us.auth0.com/.well-known/jwks.json"
- name: OAUTH2_PROXY_REDEEM_URL
  value: https://burrell.us.auth0.com/oauth/token
- name: OAUTH2_PROXY_SKIP_OIDC_DISCOVERY
  value: "true"

# https://burrell.us.auth0.com/v2/logout?client_id=GBegpb6agBLAcQ6D5bkXuJCcrDgXCEBP&returnTo=https://code.burrell.tech/oauth2/sign_out