coder:
  service:
    type: ClusterIP
  ingress:
    enable: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: 'burrell.tech'
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
    host: coder.burrell.tech
    tls:
      enable: true
      secretName: coder.burrell.tech
  env:
  - name: "CODER_ACCESS_URL"
    value: "https://coder.burrell.tech"
  - name: CODER_PG_CONNECTION_URL
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: coder-psql