apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
  roles:
  - name: pilot-dev-sync
    policies: 
      # List applications in this project
      - p, proj:external:pilot-dev-sync, applications, get, external/*, allow

      # Allow syncing applications in this project
      - p, proj:external:pilot-dev-sync, applications, sync, external/*, allow

      # Allow deleting resources in applications in this project
      - p, proj:external:pilot-dev-sync, applications, delete, external/*, allow

      # Allow restarting deployment resources in applications in this project
      - p, proj:external:pilot-dev-sync, applications, action/apps/Deployment/restart, external/*

      # Allow access to web terminal in applications in this project
      - p, proj:external:pilot-dev-sync, exec, create, external/*, allow
    groups:
      - ArgoCD-Test