sources:
  - ingress
provider: cloudflare
registry: noop
# txtPrefix: k8s_
extraArgs:
  - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
  - --cloudflare-dns-records-per-page=5000

env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare-auth
      key: CF_API_TOKEN
      optional: false
