sources:
  - ingress
provider: cloudflare
txtPrefix: external_dns_
extraArgs:
  - --domain-filter=burrell.tech,lemmy.media
  - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)

env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare-auth
      key: CF_API_TOKEN
      optional: false
