apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: poddisruptionbudgets.policy.
spec:
  group: policy.
  names:
    kind: PodDisruptionBudget
    plural: poddisruptionbudgets
    singular: poddisruptionbudget
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: Workaround
        type: object
        properties:
          spec:
            description: Workaround
            type: object
            properties:
              workaround:
                type: string

