apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-install.yaml
  - argocd-namespace.yaml

namespace: argocd

patches:
  # Disable the default argocd-notifications-secret so a sealed secret can be used
  - target:
      kind: Secret
      name: argocd-notifications-secret
    patch: |-
      - op: replace
        path: /metadata/name
        value: argocd-notifications-secret-disabled