apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploymysite-operator
  namespace: argocd
spec:
  project: internal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: git@github.com:noahburrell0/deploymysite-operator.git
    targetRevision: main
    path: manifests
    directory:
      recurse: false
  - repoURL: git@github.com:noahburrell0/deploymysite-operator.git
    targetRevision: main
    path: manifests/dependencies
  destination:
    server: https://kubernetes.default.svc
    namespace: deploymysite-operator

