apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-ui
  namespace: argocd
spec:
  project: internal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: sealed-secrets-ui
    repoURL: https://noahburrell0.github.io/sealed-secrets-ui/
    targetRevision: 0.0.6
    helm:
      valueFiles:
      - $values/configs/internal/sealed-secrets-ui/values.yaml
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    ref: values
  destination:
    name: in-cluster
    namespace: sealed-secrets-ui

