apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tdarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: internal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/internal/tdarr
  destination:
    name: in-cluster
    namespace: tdarr

