apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: tnsr-service-decorator
spec:
  resources:
  - apiVersion: v1
    resource: services
    annotationSelector:
      matchExpressions:
      - {key: tnsr.burrell.tech/tnsrACL, operator: Exists}
  attachments:
  - apiVersion: burrell.tech/v1
    resource: tnsrnats
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://tnsr-controller.tnsr-controller/service/sync