apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: tnsr-acl-composite
spec:
  generateSelector: true
  parentResource:
    apiVersion: burrell.tech/v1
    resource: tnsracls
  hooks:
    sync:
      webhook:
        url: http://tnsr-controller.tnsr-controller/acl/sync
    finalize:
      webhook:
        url: http://tnsr-controller.tnsr-controller/acl/finalize