image:
  pullPolicy: Always
  repository: linuxserver/plex
  tag: latest

hostNetwork: true

env:
  TZ: America/Toronto
  PUID: "0"
  PGID: "0"
  VERSION: latest
  DOCKER_MODS: ghcr.io/pabloromeo/clusterplex_dockermod:latest
  ORCHESTRATOR_URL: http://clusterplex-orchestrator:3500
  PMS_SERVICE: plex-relay
  PMS_PORT: "32400"
  TRANSCODER_VERBOSE: "1"
  TRANSCODE_OPERATING_MODE: remote
  LOCAL_RELAY_ENABLED: "1"
  LOCAL_RELAY_PORT: "32499"

service:
  main:
    primary: false
    enabled: false
  lb-bgp:
    enabled: true
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: bgp-pool
      tnsr.burrell.tech/tnsrACL: k8s-acl
    externalTrafficPolicy: Local
    ports:
      controller:
        enabled: true
        port: 32400
        nodePort: 32400
        targetPort: 32400
        protocol: TCP
  relay:
    nameOverride: relay
    enabled: true
    type: ClusterIP
    ports:
      pms:
        enabled: true
        port: 32400
        nodePort: 32400
        targetPort: 32400
        protocol: TCP
      relay:
        enabled: true
        port: 32499
        nodePort: 32499
        targetPort: 32499
        protocol: TCP

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
      external-dns.alpha.kubernetes.io/target: 'unproxied.burrell.tech'

    hosts:
      - host: plex.burrell.tech
        paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: plex.burrell.tech
      hosts:
      - plex.burrell.tech

persistence:
  config:
    enabled: true
    type: custom
    volumeSpec:
      iscsi:
        targetPortal: 192.168.129.254:3260
        iqn: iqn.2022-07.tech.frontenac.k8s.plex.iscsi:Media.k8s-plex
        lun: 1
        fsType: ext4
        readOnly: false
  transcode:
    enabled: true
    type: nfs
    server: 192.168.129.254
    path: /Media/PmsTranscodeDir
    mountPath: /transcode
  media-tv:
    enabled: true
    type: nfs
    server: 192.168.129.254
    path: /Media/Television
    mountPath: /mnt/Media/Television
  media-movies:
    enabled: true
    type: nfs
    server: 192.168.129.254
    path: /Media/Movies
    mountPath: /mnt/Media/Movies

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
