apiVersion: v1
kind: ConfigMap
metadata:
  name: invoice-ninja-configmap
data:
  APP_ENV: production
  APP_DEBUG: 'false'
  APP_URL: https://billing.burrell.tech
  APP_CIPHER: AES-256-CBC
  DB_TYPE: mysql
  DB_STRICT: 'false'
  DB_HOST: localhost
  DB_DATABASE: ninja
  MAIL_DRIVER: smtp
  MAIL_PORT: 25
  MAIL_ENCRYPTION: none
  MAIL_HOST: smpt.smtp
  MAIL_FROM_ADDRESS: noah@burrell.tech
  MAIL_FROM_NAME: Noah Burrell