apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: invoice-ninja
    app.kubernetes.io/name: invoice-ninja
  name: invoice-ninja-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/instance: invoice-ninja
    app.kubernetes.io/name: invoice-ninja
  type: ClusterIP
