apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoice-ninja-storage-pvc
spec:
  storageClassName: nfs-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoice-ninja-public-pvc
spec:
  storageClassName: nfs-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi