ingress:
  enabled: false

persistence:
  defaultClassReplicaCount: 1

longhornConversionWebhook:
  replicas: 0

longhornAdmissionWebhook:
  replicas: 0

longhornRecoveryBackend:
  replicas: 0

defaultBackupStore:
  backupTarget: "s3://longhorn.burrell.tech@us-east-1/"
  backupTargetCredentialSecret: longhorn-wasabi-sa
  pollInterval: "180"