apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-ssh-secret
spec:
  target:
    name: git-ssh-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        id_ed25519: |-
          {{ .id_ed25519 }}
  data:
    - secretKey: id_ed25519
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a9361bba-3865-47fa-bb7c-b0340151c16d
        property: b64_id_ed25519
        decodingStrategy: Base64
