apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-ssh-secret
spec:
  encryptedData:
    id_ed25519: AgCzY6jUpH8nyXAaH1xCPzoubc0vMny8jzbCBAVXRFEOJiMMjDExAgxHf5MrlTrV8Vl2jTWKx0WR/Y2Z387ojG63ytkwzroULP2D0aQXOzag6FbEFlfYEHDM3kN08XQD5Fi8uo9Bu63RTxLppJXGEr/kvXE/dRxgnlQDRuEASuf5o38NabSoFCWL7X4nrfN+6dqFjTr4ifnF9lPTClNEpB6A+TtqPhSs/m1HyekIQ9bUcM6DsIzCCLifrv1GkEfgWvxExggEmpr4nNQ9fqc6q9doEBCiAGLFU9srzcNaxECu+CmBZyZSiTcbMUdSi583zMC7wF1pFdo6VXyAaxw2LSCs6uNhiQ7CaauBgYa4+TK41p+3y55k1dvIcFYlwoLs6DODzXO9gXH2myrkTjOIZNlzCfRXrbWoqUjyiMKiJ7mcNd0hobq6npPVGTKG3wGy/lfjn7m+CBHpA17qALXoNNh0OCfHkUxElatDS4TKAwAOW4B/ih4PQvIcvJA+QVlCYS1T4j3d/V6vzJew7l956tERL5Vc17Sue8lufIpwJ2424mFiRUPy3fyK19AvomvKsH4goIZDRC7u8QcVr07OU+vJtQO260OuraBxXCMx+OrN1Z2LK0jWwP8gNCj5umsZ9khz3xzJGFl/WYAwYycE/Qtuit+9QOMbdEHqFMOaxwg6ve2XuCgEY/PcDkBcEPIQ5Tl5cI/oY3ynOEyEfl9O0IAATWgEDZsxjUBTNgQW+ILr8zEiFXerjerrsLNTXriMyqJSND+mzkK3CNyuEfX6KpYri2Fr6A86oKyNFG9n3t7v8XOIh5dXJJHr2qD3tAqTcRQJ+MxI0K1g82yBhCDmQ5XN3ElBhzPQx1slIUG57Zw0Y0spqHadij86VJf+XeaA77r+tS8gtcwv5IgKfdhN8fXKSY4pRX76Y3opH4vq+1KeJM4xd45ao6JW5UU7SI8agNxv/q2yIKPOdn61Jk98iI2ZJsnqqam42VNLl0pHEHma7VAHZ8xH6khQnVIRoZWkMGqhLGdG8c3oqve/IxS2wCGQECWDnHa9gP4CuaHapaBsIJDBWPk2YBs1SwI7y2QsCxa1UaSdyBTa1sfX8hxPHvL9Kw59drCTz852gdq4n57gAQF5gfxKcgsgQLc1Pt4zp9R56VX/5eZPTGD+K8435QXRc2ZUBZi7baVaRhq+D1VBhXwlE0GEIM7lhjX/4SgjsvSyVsA1OaDOP/bWPivCSY6+P4edf8HzK/hcYrQ=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: git-ssh-secret
    type: Opaque
