apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coder-postgres-pvc
  namespace: coder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: longhorn