apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  target:
    name: postgres-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        postgres-password: |-
          {{ .postgresPassword }}
        coder-psql: |-
          {{ .coderPsql }}
  data:
    - secretKey: postgresPassword
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a9361bba-3865-47fa-bb7c-b0340151c16d
        property: postgres-password
    - secretKey: coderPsql 
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a9361bba-3865-47fa-bb7c-b0340151c16d
        property: coder-psql
