apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    postgres-password: AgCdsnobG5e8evw6ffoAArq8ituWRE6v/jSeMFSq1Yf5sIf28aEoBLsn5PICuxl8KjG/VY4SZlkLyd/XLdyeGa/P4kw+0wDS/DtQ0XPHCIGUb2ZAkD53Ej/+IKWSgaevhgza/AaxbYNAdA2SBc1ols8b2f0ASBZET6Fi2QkKHO6nltbsF7piX6TvTe4MZazTwcJPk6+dCU90riXxWCTjs3j2MYFqCD3iRaybqy0s0VNZ8p6d9IK/f8FOhRx5dRmb80Y8GOQ6SzL4jcZjYyUY9vyDQA2cin4kNTVstfOAm5BmWyinCIV8BNAK/Upuohb2LcCx4dcn0ojnUwiVC76VH9aJ5vBNLhkEO6Yu0wuYMVwnttGgbjcutXFE4+kaedZw1biL9ti1K794/dGAwTRh3C+oAxeRopMkkGkUFFVlYVxL2yN9xDHfeBaQinCoGV3ke3wiK2Kv4NAanuvH6He7pSguAW9yMGkFWrc0suQ4G+P1Hsb36+SI859KavTfTjtOD8yh65KKKoEuJBUpSAJg+qT9tf8J37YV8CSkMphkXM9Q2+zjTGYaRJVF7VlM+QunO6vONl6OFcOu0yOV0U08J2AYTerIyd5ro2zJ3g65YfOcuCXz6tKUq883FwdCSHsa+uEc/tTn+t5i9/Zd0lQMcA3F1pl1BS3oLm5PuuuscerfjwiUYpcSSeKxRVsQISm+eZ1e6xBtIAV/nbpIMmUxUKKl0+H6FA==
    coder-psql: AgB+Q3VopPuIzksnh6I3r9iflIPECpCHkedbE3cICjjRGgkqQAcYppjW9rlJbf+zxaXUQkdTmnhIfWAgwqgc9P9J4dNCHCU51TXEPBmFCDegJQavFAzABkiOmPKtNxhSSboTyGAsGRm+lDz+Hlm6KAqCWeNBNF3kMgKhZSZ645LqO5DU4cI1C9mHqKHs4ilOxGajl0mUVsSzyUCSGcBV2W3r9dxPY2011r1qspGteWvPhesw6XjR5nXdLu+i338LnFjoy21IZVuWnzikvPLfyURrbtz6zDyXP/V8Bxt7rWzZGRNUlfQbH1pf9Tk5MWY1BFKTSGtKeFjMjgWfjyC9PAEFUDCURT5XNuh3BzknxHfei6nEJSmU2faXKoXORof2Lk8yLwD9QicocsbjGsqA3ka1LMj0rgmRXP0opqHVJvArrf8d9wHkqLpgz51v3xWjmFofsnaHREyBBfVSd04lOQ4BI4qigV9Pf+xDFCaHzcDi7b1x0YfFcZtEaJ1hDcn982HXqvCKgaQM/TlqSjBbeIrZMXf3YHz83Tv0XSuRjbJBUe97m94RGO3aaLOzB93emAN2JDcG/HxGwAtKBvfVBo3Zf01ZVTFmbAoT7n5rRxjtfn1UTBqe5hGelS6M0PtvBWKO48/30ohuM8WruZ4Ro7HUCKQKPHunAmFQl4DVlzJo5Kqs8HWznUckBl3PUPyHn1fwuU+mCzLWw95NTtPEOpJvrXBPnYQwTMIoNeYCTTB5GO7Hf8avuYuHt6z1TM5uF6+R2w1x3H6et8nUNPyEZgcc5d3x24ndx64AwFAvHQprUTrpF0o=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-secret
    type: Opaque
