


apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-prometheus-rules.yaml
  labels:
    release: prom-stack
spec:
  groups:
  - name: argocd
    interval: 10s
    rules:
    - alert: ArgoAppMissing
      expr: |
        absent(argocd_app_info) == 1
      for: 15m
      labels:
        severity: critical
        namespace: kube-prometheus-stack
      annotations:
        summary: "[Argo CD] No reported applications"
        description: >
          Argo CD has not reported any applications data for the past 15 minutes which
          means that it must be down or not functioning properly.  This needs to be
          resolved for this cloud to continue to maintain state.
    - alert: ArgoAppNotSynced
      expr: |
        argocd_app_info{sync_status!="Synced"} == 1
      for: 12h
      labels:
        severity: warning
        namespace: kube-prometheus-stack
      annotations:
        summary: "[{{`{{$labels.name}}`}}] Application not synchronized"
        description: >
          The application [{{`{{$labels.name}}`}} has not been synchronized for over
          12 hours which means that the state of this cloud has drifted away from the
          state inside Git.
    - alert: ArgoAppNotSyncedShortExample
      expr: |
        argocd_app_info{sync_status!="Synced"} == 1
      for: 10s
      labels:
        severity: warning
        namespace: kube-prometheus-stack
      annotations:
        summary: "[{{`{{$labels.name}}`}}] Application not synchronized"
        description: >
          The application [{{`{{$labels.name}}`}} has not been synchronized.