apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: email-alerts
spec:
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'noah@burrell.tech'
      from: 'alerts@burrell.tech'
      smarthost: smtp.smtp:25
  route:
    group_by: ['alertname']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 2m
    receiver: 'email'
