apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gmail-secret
  namespace: harbor
spec:
  encryptedData:
    password: AgCGk9JuZyW5VFhqkub3tqs4Bg+M/HRWD+oztJTtXpEb3kOHzV6MS9/SPVwXwYJpJzrj3wIDq5VB/a5Sspi5WWxSe+bRgwkbUpmXWRwCbFhAwDBTsCimc3ILGlNvTzPh8qXTvqqlWRw5kgDBmrHQpcPUmFI+hqpjnI6qj6ixlFJxluPz0BfDJEC+mqRhUCdmrQKkZeTVFQWaFLQwaZMl/SYtFGj8h8DhlzCvEXxyshgVBEcx10hsjJHgKbLukByk0GEGEqJJdGFGPyYp3n20jgBMQ4rWmDj2GdA2P2VkTDNtkO5SqSD36jhaCaOVpILJ84riRDhGl6+I4/5yvLN3IIWKOFruYm82eheYDOPgXoMIcG0JkOtKpJzB/4hnXsC/nOu4Ka0kSyKfWVUGHvL5e0ysXeIhzlQsm0m0gW4VfeHoVRmihnF3KeJ1ONDHvzKN+k8nG770vqFNIf83y1wZ3kvKoykDTHjg8d0AZRtWLw+SnZ5fexKSiZlJXuoGgmKlhiMrqhDjlOFbX/t1RVjYJ9bYHKx5pEtLZZF8EA1+wY0P0OAcjvPFlhWwsJ+chK2AusH3Ro1fPG5TYZofoJJgzQFkJfBcMwBK1DU9fp92O5TJpWQV11sbfyCQ8FMb2+BhpiY7vkHECa2AWczGP2U9mhJO+tZTrf56zWiea0W7JUBlnGTsyRQ6mLInzAMUk2MkIV0OiBHskmk99g8Y+nv50C1L
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gmail-secret

