apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: chia-node
    app.kubernetes.io/name: chia-node
    app.kubernetes.io/version: 1.6.0
  name: chia-node
  namespace: chia-node
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: chia-node
      app.kubernetes.io/name: chia-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: chia-node
        app.kubernetes.io/name: chia-node
    spec:
      automountServiceAccountToken: true
      containers:
        - name: chia-node
          ports:
            - containerPort: 8444
              name: node
              protocol: TCP
            - containerPort: 8447
              name: farmer
              protocol: TCP
          image: 'ghcr.io/chia-network/chia:1.6.0'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 5
            exec:
              command:
              - /bin/sh
              - -c
              - 'chmod +x /usr/local/bin/docker-healthcheck.sh && /usr/local/bin/docker-healthcheck.sh || exit 1'
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 5
            exec:
              command:
              - /bin/sh
              - -c
              - 'chmod +x /usr/local/bin/docker-healthcheck.sh && /usr/local/bin/docker-healthcheck.sh || exit 1'
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 3000
            initialDelaySeconds: 600
            periodSeconds: 10
            exec:
              command:
              - /bin/sh
              - -c
              - 'chmod +x /usr/local/bin/docker-healthcheck.sh && /usr/local/bin/docker-healthcheck.sh || exit 1'
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /root/.chia
              name: config
            - mountPath: /plots
              name: plots
            - mountPath: /chia_keys
              readOnly: true
              name: mnemonic
          env:
            - name: TZ
              value: America/Toronto
            # - name: service
            #   value: all
            - name: log_level
              value: INFO
            - name: keys
              value: /chia_keys/mnemonic
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      serviceAccountName: default
      volumes:
        - name: plots
          nfs:
            path: /Media/Storage/chia-plots
            server: storage.burrell.tech
        - iscsi:
            fsType: ext4
            iqn: 'iqn.2022-10.tech.frontenac.k8s.chia-node.iscsi:media.chia-node'
            lun: 1
            readOnly: false
            targetPortal: '192.168.129.254:3260'
          name: config
        - name: mnemonic
          secret:
            secretName: mnemonic
            optional: false
            items:
            - key: mnemonic
              path: mnemonic