apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-ssh-secret
spec:
  encryptedData:
    id_ed25519: AgBmenGG8cPbtq8z4MB2LBTQZFFZxpP14Tt3TUaVRt7sUZjNbcErZb8kmO1+bbmRNS2kEHhQ/Pev2Lk9CHBVWpNuzXd7pvv5Z+GN1lJigLIr/bITEww6x/zxmaO+3ICGGbYPP3Bbhm4fdOTyNGXsLQpOafpHP/VpeGU8fCq59hnCXT1Zg5LtasdYNO1Yn1imMKLQTYakGOooPReWAWazeqpAef57W0kzhjCESD2XlkkAH8MhHEBNqQqGC0O0gRncLQ7N/HLuFqfTY5tTWYlHszW166+Q7vQoEf1zUnw2pXvkCqp3LsPKfoURI8soTO1SpBxFJZMEfBdcfMLlQB3s2N5X59JyFxzZlPgocIBVxorQvhv2EzSgO0nFkJdRrFO2onbAe+rVoD1A9qgBgP/KUiF6J9v46ZYn4/TY86gf1zCQcIjPaDlXVNicy2p96B/ZXqHM6Lq2tnlRSTbw2kgNKhr4D2YYdgCnFtUCRaVkdAKMw7Qdvq2rZxb3M2/Lmint18A4w/mnOdRv4SAH5+iaARUGDlTNn3mSdnfFCHLI2ujnyLLMsEjh1yUS9o7sLQ3F/kaxXiOKpmuJFr7zimUK8pIyrIoyMLdFDWCMpCziN8V7osm+gLskB+xfbA86E4Q31pyzVIBvl+inBEixEADagGwOgxLr9AybsAjp4N/Z9bX0Ni7L0rN1Y8ZkdcR2pJRHsqrwZjJcPJlkGhHWerP0WbObZloNo/6BlpbFfxxarYuEmfuWp9KcLrvlctijtsdBtWA2r1sbgQbDCd3v2tKWqLSgk7rY2s5v3tdeSjsKwrVvxekxS99CWZXFkT4SEaJYtcymfQclDVfLHhZCdIgevbxVxoMgfm8vwoZZeVtCXWJcz7KI4H5L+2GjuCvPXqYIrwPhsGZDnvXGiZlrsll2dfIEa/srGyAg22LGVu+h7ycQ5UTATMTXspNuBeK6kfaU9fGrysr8Yb5FqTa65VMpIm6c/WgYWJn4qkWpI5erVfqOKcRjv85y9F9gKJjfPvoN6CyfRnNZwHHHG/lQR9YYFBXDt3u062ge5ticIlTQgTrBepwiTTm2jcsbGPH3XQ0RGUEy0eb27ZevBBazVBLYIOASkMqPZRc+Uu7lTuGU2uqAKJby0WeXDFjOoJ66J8wFlXf5UJ1YgxEMSwFt2Jw2kGlcejjh1vFGqM4Ntoc7nGkPcVjW8VrHTfyBmg1DcijEUKjwZkeruJwbGol+TJlR/nu0ioHxAwLTwKo+eA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: git-ssh-secret
    type: Opaque
