apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    postgres-password: AgCdsnobG5e8evw6ffoAArq8ituWRE6v/jSeMFSq1Yf5sIf28aEoBLsn5PICuxl8KjG/VY4SZlkLyd/XLdyeGa/P4kw+0wDS/DtQ0XPHCIGUb2ZAkD53Ej/+IKWSgaevhgza/AaxbYNAdA2SBc1ols8b2f0ASBZET6Fi2QkKHO6nltbsF7piX6TvTe4MZazTwcJPk6+dCU90riXxWCTjs3j2MYFqCD3iRaybqy0s0VNZ8p6d9IK/f8FOhRx5dRmb80Y8GOQ6SzL4jcZjYyUY9vyDQA2cin4kNTVstfOAm5BmWyinCIV8BNAK/Upuohb2LcCx4dcn0ojnUwiVC76VH9aJ5vBNLhkEO6Yu0wuYMVwnttGgbjcutXFE4+kaedZw1biL9ti1K794/dGAwTRh3C+oAxeRopMkkGkUFFVlYVxL2yN9xDHfeBaQinCoGV3ke3wiK2Kv4NAanuvH6He7pSguAW9yMGkFWrc0suQ4G+P1Hsb36+SI859KavTfTjtOD8yh65KKKoEuJBUpSAJg+qT9tf8J37YV8CSkMphkXM9Q2+zjTGYaRJVF7VlM+QunO6vONl6OFcOu0yOV0U08J2AYTerIyd5ro2zJ3g65YfOcuCXz6tKUq883FwdCSHsa+uEc/tTn+t5i9/Zd0lQMcA3F1pl1BS3oLm5PuuuscerfjwiUYpcSSeKxRVsQISm+eZ1e6xBtIAV/nbpIMmUxUKKl0+H6FA==
    coder-psql: AgCTKR0sUEgUxuYjeehp3ln1sb4rhfekq0iv96AmiHyRbnCd/uUAVzl8EwAp5FwOMQbdIEyDDAjVlNbIgGVQ4U/WobQ6r5PfWaVODXiRRuOEib+FswZzWPQ/BKJuSv5QsoecSA8mWJbK+lJLstWPfF58s4a6kCx1R+lwB50bbAzCfhJCTmlqa++LfUqV4JuiliW/tn2BcrZS7f8uTnStXV9aDChei5fSmAVRsJ2yv2NQ+HDFsSZubOAOkhN3eymPA5sDSFapjk9MpTsruNrDZmmMvI56J/7loFXv0+f16FTurSkheRCrE8dIXLfNlymZexMrb5kfwakJ92Fxublmrw0wxtvAQ8dWNaAvjXEGnhjGVFXeI41+c3kzxLA0UiqAqQqZRathwxEi0LOqMMZRJooqSvjClk7XJ8AyIfA7YplF9zcZ7tB7T/Hw8ZEvO6JYKs3EDE44Rzz14w7+y2l3EtFi5okp+mUeUNFzNdxhV4wmIqL8KXsmDC8fb7lqGz28o35BEYTlqqfzFwrID0fqXICnlF1tzc4XlTb8i4KXZmnGlOptsmMY5rlhnwo5klx4/JRRSWgIbPtDoCABLYGxcakX2IO2j+2VStIpXmh4zOKpnwD5rPWb3V7yfXTECFOcy5ExwicQcy2yPvGBl277cJUa/1+Tye4uKvhX61cvmY3ppaRW5n+Q3TP6WbZ8ePLkhYO8vU7e0+L92q/xvku3rJWOs3WepesJsC/s43ulMkc3PwdbaNvPM1TFoZR5jjkUHS0ChqCKBmkuNlXdLH5MC7oEZVvUQ0ul34Xln9WdtOdVlO4/
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-secret
    type: Opaque
