apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    postgres-password: AgCdsnobG5e8evw6ffoAArq8ituWRE6v/jSeMFSq1Yf5sIf28aEoBLsn5PICuxl8KjG/VY4SZlkLyd/XLdyeGa/P4kw+0wDS/DtQ0XPHCIGUb2ZAkD53Ej/+IKWSgaevhgza/AaxbYNAdA2SBc1ols8b2f0ASBZET6Fi2QkKHO6nltbsF7piX6TvTe4MZazTwcJPk6+dCU90riXxWCTjs3j2MYFqCD3iRaybqy0s0VNZ8p6d9IK/f8FOhRx5dRmb80Y8GOQ6SzL4jcZjYyUY9vyDQA2cin4kNTVstfOAm5BmWyinCIV8BNAK/Upuohb2LcCx4dcn0ojnUwiVC76VH9aJ5vBNLhkEO6Yu0wuYMVwnttGgbjcutXFE4+kaedZw1biL9ti1K794/dGAwTRh3C+oAxeRopMkkGkUFFVlYVxL2yN9xDHfeBaQinCoGV3ke3wiK2Kv4NAanuvH6He7pSguAW9yMGkFWrc0suQ4G+P1Hsb36+SI859KavTfTjtOD8yh65KKKoEuJBUpSAJg+qT9tf8J37YV8CSkMphkXM9Q2+zjTGYaRJVF7VlM+QunO6vONl6OFcOu0yOV0U08J2AYTerIyd5ro2zJ3g65YfOcuCXz6tKUq883FwdCSHsa+uEc/tTn+t5i9/Zd0lQMcA3F1pl1BS3oLm5PuuuscerfjwiUYpcSSeKxRVsQISm+eZ1e6xBtIAV/nbpIMmUxUKKl0+H6FA==
    coder-psql: AgB5n43N/zTaJe8PlbyQf9Zalf9+kqzXHEDooYlXthjpT1aQIUNakcEWDnmv0876oyW2t1SA55I1AgQ8AFFWuY2RQk8VlI8KUuBH048ENdAJoQpem5sOF4IriBHEMZRM4AdIG/W7A9AtEI7AgFQRneOLhuoe7UPl+t6nDFvYkxdBmef0TkrZbdD49V4E4rRLKMg7bKxtw7SZ8svbiVN/y0LEZrZfKBBCdnNE+0JxJW/AASOMaLkqP11nl6KdLySEX1TZ9KehomcgR1tx4xPblVEgHKoGwCnLBwlCpDpkYUpWTix144G13dMSJV9Qf3C9GvNBUwVqLF2UYdP2OHZW5vD5TltgwQuewaUUWDYgxy60CX+fZygwkqv6byle46rl3AmKJXN3loYKU1gCx5BGjxwLu7QRFhwsjD8EjTpcmSeMqn/YxMbNDd6Ylow+1sMrxemcrWFOIY4a3jvmn2mNXxpZ+pGSC/3oE/E0UEGHZvxiLU8ldAOoBkYPwyk7TOlnhwaFVTsE3EHAQVwtstvbb+6UO9ZojeNVmVMwAkt2mjZE5igz931497dvBP8B+nWuyqkt79n6EMtnO00yBx8rlsCh2O+uo+lO/gBOWgLT1hAaR2Sn760o97sbBT07VaR9nXVLoChKQdKqcL+mnjhc0Tz1To/idwRb//M0iH+WeaEqGTDyCwf9C4cmBDteMGZpHz9SijFvH9cF+vrF8LdRe74+LfScUiFB997UJZ7IjV7P+KYbI/qJV7mgaSuh56Cz72xL7w5yEsUrE2z/O9MttBHXuW+gvGhy23U+0lh2DHfMxAQzaiV0PJqV
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-secret
    type: Opaque
