apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-wildcard-cert
spec:
  secretName: envoy-wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - burrell.tech
    - "*.burrell.tech"
    - "*.home.burrell.tech"
    - "*.k8s.burrell.tech"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: envoy-wildcard-tls
      allowedRoutes:
        namespaces:
          from: All
  addresses:
    - type: IPAddress
      value: 172.19.0.254