apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: gateway-helm
  releaseName: envoy-gateway
  namespace: envoy-gateway-system
  repo: gateway-helm
  valuesFile: values.yaml
  includeCRDs: true