secretName: wireguard-sealed-secret

wireguard:
  serverAddress: 172.20.0.1/24
  serverCidr: 172.20.0.0/24
  clients:
  - PublicKey: dRw2kgfUv/84I2hEH9tKqjUT3EMneqhpNGVfg1n30Qc=
    AllowedIPs: 172.20.0.2/32
  - PublicKey: QSZkHVpgOs8MkozANiAvBcvKDED0ZKujicjYOIfMfQ0=
    AllowedIPs: 172.20.0.3/32

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi

securityContext:
  privileged: true
