apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: wireguard-sealed-secret
spec:
  encryptedData:
    privatekey: AgBwrmKCaZkxlopdOKIp1rx807gvTJIo4om+02neVHDQSdzjibXcMVs7gEhUKJlyUDDGrqoQDssti6QmJgf3vZZfH81fwlaln1KYCgrmh169RSEVR9WA4CBWSj+mgxKV4kSn4rKh9GKOcPcHr2UIgl6VfPdL4Y0moKTviJjWv8gx4hOwFR6XCcH7+L30BS3cx8yz2b9qUn8csbG5Kyd38r35cY7zFOvorV8SRALxOhHjjE0fWa0YIsqWQiE77+WHZe+Vr2wCXVoAoJdbEImXPzb5BCvZuw1Am4R0S5qZLezHTIlPkPrnGBJQOLCrVmNkHG0c3BfT86e/eqy/y88fVMitu7FMWjpHOhaiKcxNQCIOpp506bETcDzREr/tlMqzpDSC6SeFosT+1N+b5E7UGd/GGbA/3D/ySfK4GSsDWVveJG8zl10s5vK5xobZTo15Hdr92wia0u7uS9QAkki1iAonalIaejLpmpSGO280N2lMsnR0sHzy3WosmuRMvVA4nxlVowafVy9l6cHpePjjzPNaYU7i5U9goxoYbi1yTNZ9UoyMk/9dOoyLinkhUOulsaSZd2Nll8jHX9K1+b2fNk9Yvvq1+KZrdMtuHYoEXVxUsbDMKiYfiSaE2Aty9+bIlEpWZ0rLdzM8xXDO7lmgtc2ytsYscArew7R2wQE/Qk7YyRasMK9SR3eamvg/c2RhEVYB06/uYeS9DZiY9CoD2mSReGBj81VjuW4wMFeV8IWkutNGee3URf/vlJecZQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: wireguard-sealed-secret
      namespace: argocd
    type: Opaque
