apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wireguard-sealed-secret
spec:
  target:
    name: wireguard-sealed-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        privatekey: |-
          {{ .password }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7b933cb2-0c95-4dd1-aede-b034016816af
        property: password