image:
  pullPolicy: IfNotPresent

env:
  TZ: America/Toronto
  RUNAS_UID0: "true"

service:
  controller-tcp:
    enabled: true
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: bgp-pool
      metallb.universe.tf/allow-shared-ip: "unifi"
      coredns.io/hostname: controller.unifi.home.burrell.tech
    externalTrafficPolicy: Local
    ports:
      controller-lb:
        enabled: true
        port: 8080
        nodePort: 8080
        targetPort: 8080
        protocol: TCP
  controller-udp:
    enabled: true
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: bgp-pool
      metallb.universe.tf/allow-shared-ip: "unifi"
      coredns.io/hostname: controller.unifi.home.burrell.tech
    externalTrafficPolicy: Local
    ports:
      syslog-lb:
        enabled: true
        port: 5514
        nodePort: 5514
        targetPort: 5514
        protocol: UDP
      discovery-lb:
        enabled: true
        port: 10001
        nodePort: 10001
        targetPort: 10001
        protocol: UDP

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16,172.16.0.0/12"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
      external-dns.alpha.kubernetes.io/exclude: 'true'
    hosts:
      - host: unifi.home.burrell.tech
        paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: unifi.home.burrell.tech
      hosts:
      - unifi.home.burrell.tech

persistence:

  data:
    enabled: true
    nameOverride: longhorn-data
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 10Gi
    mountPath: /unifi

mongodb:
  enabled: true

  image:
    pullPolicy: IfNotPresent

  architecture: standalone
  auth:
    enabled: false
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
