apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-auth
spec:
  encryptedData:
    CF_API_EMAIL: AgAFKpoS3iJ5lcKL60Rvx/6HwrjLrBPs8D6cYbB8r5R9owYljJV5HfNhn8EfkbnecESoqfDKUj25JnN7qD+HFJCUpHqF0FtlZbjYgg4vYwmcphrU7m3HUc+8KH8OaS038PaIBSBMXcSAZX7/Zzar+mt+RmwRxImnaVk+PGRPpsSjy8HFQo2qJN72jmMK0iu6ZSk4q1ZqM6Vvly4M0TKNCGEYoX6TaoJYBquXr5ra6XLAIbf1Uhh/E2HyPkjjTT4w6w1itpQ3lJxtBroma186xehNhP8GDPR5xHE6b7KG3/UdbpULSvzSaIXrfGkCuQILahyFOMdRtlf+iRwkC8UaVpps0X1ZrBxITWEAl2xJ3thwkgZpWaQK/QavHHQCTWHAsJbry6cQ8SM6MQMXQKSLZLWu2PB+kpvSP33v/5FWQb2WIjXziFRNjejyT8SxJkHGyc2bWk/dW4cyMYODOc+V8KTqizwjdVvcxx95P9ph3NUlamMble1g7uWn22A/bnGrWbKnJlg2Zyyr1EXO1PV4VEyJ4YI7dqNiApgV0Bf/17SwT4nwfnqU0/mwfiRd482ENRQfZIjRHdD04A3A+jCO82i7262ZhZCd3rxGEnUj8sK8TfYZ/ZaYOBHpBXLzThYz5t/sRsc0QTYgkqu5Z7VwDjHtDYeeaQ/apn//r6Zj6QEU6DF82OnVr5rEdzdX7JYAWE69ZkSxOmYlci/5G1myv6ldgGubFAIr
    CF_API_KEY: AgAo/gU5w3LBI6SwcT4ndnJKH5Yx2wmcGsx3Re9Au0KZc/9xPRdoK/q+Zt4IhmUNinSgucUV9KkRn1QNLLXJEdgKyIsYVvzuddWbMFLdT3o3tsYSMkbgUXXtgLAGBRYxAmtqp2rHFfMXk3FNEI4vzfVPtW8OrX7D69ln3IymbjxRhDiQT28HoUTIRIldsYIS+fyKEJL5B/gPkWPWTa++a5JL+eB6IMj5JBqnkvrxDqJYguwTw+tGJcNZXOVimg41aO4bSGDQadYmwDh14LYModUGr8qA6SSaY0eUF0kJe5cnmTFXl6EUipIBadAcvayZnYhfGvHHxWhwHZWMWtCtXOKvnKHbsksy65obkcsfySB7nFyxRwD+f6+lhWqKNDBLzOeJ9D51lF/rDLU+8fYQpuuFDaYwbjlibv8UbNuZ1SCFFvzn54ZpGEAZYf6Ir9N0A6SegAxHwsf0MLCNoQKl3aSOUrkEXv/yDcUEj4XRqEZAzQ9ZF17R98bC7jwtRt7w+YGUlicHnECheVudnsg0Tb0cpjKVw06bisgZin6DApJWgu+uAhCQOqC1d2y6VJov/NWHZyLocinZ0eLaGAWJN/C9Uii2ezm3Kjz/qw3/0oafTjvZdye9o5xmW65LZeTiHoAeLJSvr8Ly4HYfWnBhvTkVcbysSyrn8LLkdGiKZW3IuV38glYip1l0yuZTkzhg0ufmZkMD3iq71FzF2RQqO2FsQCLnKPOAi8qXBGUAUVfdBRiwJF0b
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-auth