apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-auth
spec:
  target:
    name: cloudflare-auth
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CF_API_TOKEN: |-
          {{ .password }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 688cdddd-0a97-4119-bad9-b0340149715a
        property: password
