apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-auth
spec:
  encryptedData:
    CF_API_EMAIL: AgC5MtFpjBr6LLDnudzkXXmM9JX+cbo6zzj92JYv3wzFTy6x1EcNS8peNrCY4ha6ogTKSvHXK5ygGfU5e5ndRgyHp7sy/u2MSD5zEu1mkUDcsmKOB5ZynTCS3iEP4SqNN5MaEBjFJyCCa+gockThlA0ECBw/EHxRsMhclDLrAl2URa3Nh6GdmzavGHVHMCxqirTVQM2siDQ4doVlWjcrq3mAAWrh9SKVnMQViLGWaxxsQxH2VjV/CRjsZ77FayMu4d+Dt5T+mrkmhq8tlfPm/BHsN3JAo2IMfsiBhuKfq5mxwFTcfp/BnMYDaWyVEsaBoceHrbcTBlW0w82Lw5Sr1H2dDiDSlWof49VvzlYPA2us11nMgJNPU7fDlgUUbExl3BEdsqFSYlsVMfZis4AFB6WbGHMJ/3XmnhHRtdgDAEWoiDRQCxm3zwqWIdHHsSZm1Pj+KAB8cteD4PcrKMBfzIav5jOqb8Mh3rRzI953L25be5DVxKC0YjTL/OdnjG10M5XteggTDnjXHEhZfRI9gDavLkSLEU0J4fjXRLeNnWtlfD+U3VjvmQz+Y2wmA/beNTuVNmxInmlvFUvLyy2mZqBF1uoCOBUkTSZdDnVo7hZG+4yWSsvOzG8HmyepATiTF336Xm5+1mzV6cf0eS83XSug+buYAlzbjj+1MvHsnUaGTmjEy7odhagVuPNcIpnPMlrKg05sAlqUgPjs1g4d/RY5PuK0WD0I
    CF_API_KEY: AgAo/gU5w3LBI6SwcT4ndnJKH5Yx2wmcGsx3Re9Au0KZc/9xPRdoK/q+Zt4IhmUNinSgucUV9KkRn1QNLLXJEdgKyIsYVvzuddWbMFLdT3o3tsYSMkbgUXXtgLAGBRYxAmtqp2rHFfMXk3FNEI4vzfVPtW8OrX7D69ln3IymbjxRhDiQT28HoUTIRIldsYIS+fyKEJL5B/gPkWPWTa++a5JL+eB6IMj5JBqnkvrxDqJYguwTw+tGJcNZXOVimg41aO4bSGDQadYmwDh14LYModUGr8qA6SSaY0eUF0kJe5cnmTFXl6EUipIBadAcvayZnYhfGvHHxWhwHZWMWtCtXOKvnKHbsksy65obkcsfySB7nFyxRwD+f6+lhWqKNDBLzOeJ9D51lF/rDLU+8fYQpuuFDaYwbjlibv8UbNuZ1SCFFvzn54ZpGEAZYf6Ir9N0A6SegAxHwsf0MLCNoQKl3aSOUrkEXv/yDcUEj4XRqEZAzQ9ZF17R98bC7jwtRt7w+YGUlicHnECheVudnsg0Tb0cpjKVw06bisgZin6DApJWgu+uAhCQOqC1d2y6VJov/NWHZyLocinZ0eLaGAWJN/C9Uii2ezm3Kjz/qw3/0oafTjvZdye9o5xmW65LZeTiHoAeLJSvr8Ly4HYfWnBhvTkVcbysSyrn8LLkdGiKZW3IuV38glYip1l0yuZTkzhg0ufmZkMD3iq71FzF2RQqO2FsQCLnKPOAi8qXBGUAUVfdBRiwJF0b
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-auth