apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-auth
spec:
  encryptedData:
    CF_API_EMAIL: AgAFKpoS3iJ5lcKL60Rvx/6HwrjLrBPs8D6cYbB8r5R9owYljJV5HfNhn8EfkbnecESoqfDKUj25JnN7qD+HFJCUpHqF0FtlZbjYgg4vYwmcphrU7m3HUc+8KH8OaS038PaIBSBMXcSAZX7/Zzar+mt+RmwRxImnaVk+PGRPpsSjy8HFQo2qJN72jmMK0iu6ZSk4q1ZqM6Vvly4M0TKNCGEYoX6TaoJYBquXr5ra6XLAIbf1Uhh/E2HyPkjjTT4w6w1itpQ3lJxtBroma186xehNhP8GDPR5xHE6b7KG3/UdbpULSvzSaIXrfGkCuQILahyFOMdRtlf+iRwkC8UaVpps0X1ZrBxITWEAl2xJ3thwkgZpWaQK/QavHHQCTWHAsJbry6cQ8SM6MQMXQKSLZLWu2PB+kpvSP33v/5FWQb2WIjXziFRNjejyT8SxJkHGyc2bWk/dW4cyMYODOc+V8KTqizwjdVvcxx95P9ph3NUlamMble1g7uWn22A/bnGrWbKnJlg2Zyyr1EXO1PV4VEyJ4YI7dqNiApgV0Bf/17SwT4nwfnqU0/mwfiRd482ENRQfZIjRHdD04A3A+jCO82i7262ZhZCd3rxGEnUj8sK8TfYZ/ZaYOBHpBXLzThYz5t/sRsc0QTYgkqu5Z7VwDjHtDYeeaQ/apn//r6Zj6QEU6DF82OnVr5rEdzdX7JYAWE69ZkSxOmYlci/5G1myv6ldgGubFAIr
    CF_API_KEY: AgAyHdHkAJLeeHecEYRmtgUBCBdwBn8dze0g6j6cN2gDb0YUGWZv9Gznv4kxndhumQjRRr3Pi1HZamKcjB1sQRNfo8pxgH6JceZi3cXHQ8+HcevxSc54FrcUUXO1owx8Aknledgr9QxEL7DDDJQEHs4wkgzLLxGeB9XUgDD0TJW0NF9YSkBdLaSi79UuCunwQJ466qfTlWAiZbCSHShNXTHF7/V2RWQhlVrvhw/LwpSgmjtTGh2FdwZS9d402/v8T2Zmp2I9F+aLNAcxrkug94ORpxJWRk1cLFhHsM0Djk82QnvDu4zMdnaTeprIFB9RDuLSNigraG+veeWzmTSVxqKrK/i2LdFtI29aBWy31a1M4rpZ8n5NA2L+MhaQh9ezijV6i6ehykTi4kqwApPg1SFrIjWi1GXhz0nov48YDU2I/nwq4I+9nWTvRmxWIplcV7MjYSIsjnjN8uyUxujCVxA3ZzmtGS0HCPAzSe8LtkzF6JcN0pb1QwC3nl1TEbxwQVt46mZvU9egTg1UPU8X/afyRUY30LL1fdGu9Cp9SuTWMAVZbZ5/XpGUICwHYYMlLag0N72A+nWjuoSeElWOABZ0u/E+Zl2AOGu/W/0FqbQ3v/gWotIt3NfG9JaX1JRagIxMj7e8sXrA1gKjLU6NUts56Nmkdu5rLxZblYiEmFx6b7jwD68qyDQd3SdicJmpnEFwKbOVsJlXq4xQj4o2nRTEanKy4x9ExLbszXGNQx/U/jb3bu3B/AcT
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-auth