apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml

namespace: ingress-nginx

patches:
  # Make Nginx the default ingress class
  - target:
      kind: IngressClass
      name: nginx
    patch: |-
      - op: add
        path: /metadata/annotations/ingressclass.kubernetes.io~1is-default-class
        value: "true"
  # Use the host network to directly expose 80 and 443, without needing a high port numbered nodeport or loadbalancer
  - target:
      kind: Deployment
      name: ingress-nginx-controller
    patch: |-
      - op: add
        path: /spec/template/spec/hostNetwork
        value: true