apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-secrets
spec:
  target:
    name: harbor-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        HARBOR_ADMIN_PASSWORD: |-
          {{ .harborAdminPassword }}
        REGISTRY_HTPASSWD: |-
          {{ .registryHtpasswd }}
        REGISTRY_PASSWD: |-
          {{ .registryPasswd }}
        secretKey: |-
          {{ .secretKey }}
  data:
    - secretKey: harborAdminPassword
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cda66a34-2cf8-46a2-bda5-b135010e6cf8
        property: harborAdminPassword
    - secretKey: registryHtpasswd
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cda66a34-2cf8-46a2-bda5-b135010e6cf8
        property: registryHtpasswd
    - secretKey: registryPasswd
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cda66a34-2cf8-46a2-bda5-b135010e6cf8
        property: registryPasswd
    - secretKey: secretKey
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cda66a34-2cf8-46a2-bda5-b135010e6cf8
        property: secretKey