image:
  pullPolicy: IfNotPresent

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: true
    type: nfs
    server: "192.168.1.10"
    path: /Media/nzbget
    mountPath: /config

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0