apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: setup
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/setup/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
