apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: setup
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.12.0
    helm:
      valueFiles:
      - $values/configs/setup/external-dns/values.yaml
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/setup/external-dns/configs
  destination:
    name: in-cluster
    namespace: external-dns

