apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: setup
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.0
    helm:
      valueFiles:
      - $values/configs/setup/external-secrets/values.yaml
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/setup/external-secrets/bitwarden
  destination:
    name: in-cluster
    namespace: external-secrets

