apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-private
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: private
  syncPolicy:
    automated: {}
  source:
    repoURL: git@github.com:noahburrell0/k8s-private.git
    path: apps
    targetRevision: main
  destination:
    name: in-cluster
    namespace: argocd
