apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: setup
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: longhorn
    repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
    targetRevision: 0.1.0
    helm:
      valueFiles:
      - $values/configs/setup/kargo/values.yaml
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    ref: values
  destination:
    name: in-cluster
    namespace: kargo
