apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metacontroller
  namespace: argocd
spec:
  project: setup
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - alias: metacontroller
    chart: metacontroller-helm
    repoURL: ghcr.io/metacontroller
    targetRevision: v4.5.2
  destination:
    name: in-cluster
    namespace: metacontroller
