apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/setup/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  ignoreDifferences: # Ignore dynamic parameters that cause incorrect OutOfSync status
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
