apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-provisioner
  namespace: argocd
spec:
  project: setup
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.16
    helm:
      releaseName: nfs-rwo
      valueFiles:
      - $values/configs/setup/nfs-subdir-provisioner/nfs-rwo-values.yaml
  - chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.16
    helm:
      releaseName: nfs-rwx
      valueFiles:
      - $values/configs/setup/nfs-subdir-provisioner/nfs-rwx-values.yaml
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    ref: values
  destination:
    name: in-cluster
    namespace: nfs-subdir-provisioner-system

