apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-provisioner
  namespace: argocd
spec:
  project: setup
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/setup/nfs-subdir-provisioner
  destination:
    name: in-cluster
    namespace: nfs-subdir-provisioner-system

