apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: setup
  syncPolicy:
    automated: {}
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/setup/sealed-secrets
  destination:
    server: https://kubernetes.default.svc 
    namespace: kube-system
