apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tnsr-controller
  namespace: argocd
spec:
  project: setup
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/setup/tnsr-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: tnsr-controller
