existingSecret: minio-credentials
replicas: 3
persistence:
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 10Gi
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    external-dns.alpha.kubernetes.io/target: 'burrell.tech'
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
  hosts:
    - s3.burrell.tech
  tls:
    - secretName: s3.burrell.tech-tls
      hosts:
      - s3.burrell.tech
consoleIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16,172.16.0.0/12"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    external-dns.alpha.kubernetes.io/exclude: 'true'
  hosts:
    - minio.k8s.burrell.tech
  tls:
    - secretName: minio.k8s.burrell.tech-tls
      hosts:
      - minio.k8s.burrell.tech
resources:
  requests:
    memory: 4Gi