apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kitchenowl-secrets
spec:
  target:
    name: kitchenowl-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        JWT_SECRET_KEY: "{{ .JWT_SECRET_KEY }}"
  data:
    - secretKey: JWT_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: aaff9ab8-c69e-4eff-a041-b4350118246f
        property: JWT_SECRET_KEY
