apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchenowl-data
  labels:
    app.kubernetes.io/name: kitchenowl
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
