image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/onedr0p/bazarr
  tag: 1.4.2

env:
  TZ: America/Toronto

ingress:
  main:
    enabled: false

persistence:
  media:
    enabled: true
    type: nfs
    server: "192.168.1.10"
    path: /Media
    mountPath: /media
  config:
    enabled: true
    storageClass: longhorn
    size: 50Gi

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
