apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: image-pull-secret
spec:
  encryptedData:
    .dockerconfigjson: AgBobSJilSO+evc20EGOZGT2OgaghPtkI7alwCWbFUT88M6++wB6lgkDiUcGutFXPiTc0cgdgb6l1Y4r2tSdXkxT/EvvqmSVsS1w35OqA2WCrdRv2DJDOY9W29sfBwOHidAD5PsHqzwTw+GH5yxfY47dyOpgQSoZeqDQPSxF+giryXSbTzR5a1wohTTI+bJ6fhAxz25yeyHKVwLQ65WYMMlDmdCeNEPoj7oSMjX166eMZz+UHOsBaTJRB2xnFdCqIWRd6I4DXI1qdJ5U9k+XMjAFFezMqDgO93OKsd7GaqT0Fv+C6HqxcatQRDvzJFDolLQreh2JbaeLvzqFL4Y5mmHVZj0Fhg03+VA8mzcBffs1WIfi3MEdjeYBcca6YXcqum+LVuRq4k+PZ6LJygglnA53awvLgjcCA1RbfpPn84xkMNXGhaoyWvGcxTxvjBV563zO6wErIsnOvHJYZ/Wp8Mbmu02AmMH7iPSJ6Gq1Y31XuZd6do0XAUiVkI5e5guCUickjwN+ozBSjaGwprqlN818BXxTWK3CAbBbH8nr3vG1Nw4316C+KQ+LjPCLuxd0Hi9ju+49lJPX3dpyRmfRk4efrVRa3xA7rLhwbXzZV336iiISOqszs5nzN8HMuFWaqtyn1YkF+Sq7/iFPZL8wE6gFk9LcARUyWGKpKr4Rnao+7Z3FgXsP7iDt/LGwi/1zU83int5wzcg7sX7PSbsvWH1zcT40BaJ+8B+++KtnfuXY90HoMauiIf3QerUVtkyv588QolE/qHyzkWGCy77dzYMxJ049yi/lGRHzSiiVcM92jYjIreCq+IPDI9iOYq9qW6mpJ6S1/9XpePaUSmE/Z/6YfZNEX8qHV5On+KtIIDX40YvLjHrJnXo2Rayt9w==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: image-pull-secret
    type: kubernetes.io/dockerconfigjson