apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seafile-external-secret
spec:
  target:
    name: seafile-external-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DB_ROOT_PASSWD: "{{ .DBROOTPASSWD }}"
        SEAFILE_ADMIN_PASSWORD: "{{ .SEAFILEADMINPASSWORD }}"
        mariadb-password: "{{ .mariadbpassword }}"
        mariadb-replication-password: "{{ .mariadbreplicationpassword }}"
        mariadb-root-password: "{{ .mariadbrootpassword }}"
  data:
    - secretKey: DBROOTPASSWD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d5225014-5570-4413-8fb5-b41701826e1e
        property: DBROOTPASSWD
    - secretKey: SEAFILEADMINPASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d5225014-5570-4413-8fb5-b41701826e1e
        property: SEAFILEADMINPASSWORD
    - secretKey: mariadbpassword
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d5225014-5570-4413-8fb5-b41701826e1e
        property: mariadbpassword
    - secretKey: mariadbreplicationpassword
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d5225014-5570-4413-8fb5-b41701826e1e
        property: mariadbreplicationpassword
    - secretKey: mariadbrootpassword
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d5225014-5570-4413-8fb5-b41701826e1e
        property: mariadbrootpassword