apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seafile-external-secret
spec:
  target:
    name: seafile-external-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DB_ROOT_PASSWD: "{{ .DB_ROOT_PASSWD }}"
        SEAFILE_ADMIN_PASSWORD: "{{ .SEAFILE_ADMIN_PASSWORD }}"
        mariadb-password: "{{ .mariadb-password }}"
        mariadb-replication-password: "{{ .mariadb-replication-password }}"
        mariadb-root-password: "{{ .mariadb-root-password }}"
  data:
    - secretKey: DB_ROOT_PASSWD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d5225014-5570-4413-8fb5-b41701826e1e
        property: DB_ROOT_PASSWD
    - secretKey: SEAFILE_ADMIN_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d5225014-5570-4413-8fb5-b41701826e1e
        property: SEAFILE_ADMIN_PASSWORD
    - secretKey: mariadb-password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d5225014-5570-4413-8fb5-b41701826e1e
        property: mariadb-password
    - secretKey: mariadb-replication-password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d5225014-5570-4413-8fb5-b41701826e1e
        property: mariadb-replication-password
    - secretKey: mariadb-root-password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d5225014-5570-4413-8fb5-b41701826e1e
        property: mariadb-root-password