apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret-private
spec:
  target:
    name: cloudflare-api-token-secret-private
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        api-token: |-
          {{ .password }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: fe186eea-b302-4e23-a697-b03500f6ca2c
        property: password
