apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-gcp-sa
spec:
  target:
    name: longhorn-gcp-sa
    deletionPolicy: Orphan
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: |-
          {{ .AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .AWS_SECRET_ACCESS_KEY }}
        AWS_ENDPOINTS: https://storage.googleapis.com
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 8cf3b09c-6cc7-4d24-a367-b0ce0173caea
        property: username
    - secretKey: AWS_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 8cf3b09c-6cc7-4d24-a367-b0ce0173caea
        property: password