apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tnsrnats.burrell.tech
spec:
  group: burrell.tech
  names:
    kind: tnsrNAT
    plural: tnsrnats
    singular: tnsrnat
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: tnsrNAT is a strictly informational CRD to convey the status of NAT/ACL rule creation and information in relation to
          the service resource which spawned the rules.
        type: object
        properties:
          spec:
            description: tnsrNAT.spec represents the desired state for the NAT rule which is to be applied in tnsr. This doesnt actually do anything
            type: object
            properties:
              externalPort:
                type: integer
              localPort:
                type: integer
              natInt:
                type: string
              localIP:
                type: string
              protocol:
                type: string
              tnsrACL:
                type: string
          status:
            description: tnsrNAT.status outlines the status of the generated NAT and ACL rules in TNSR
            type: object
            properties:
              nat_created:
                type: boolean
              acl_rule_created:
                type: boolean
              acl_rule_sequence:
                type: integer
              acl_info: # Result of `show acl {acl_name}`
                type: string
              error:
                type: string
