apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tnsracls.burrell.tech
spec:
  group: burrell.tech
  names:
    kind: tnsrACL
    plural: tnsracls
    singular: tnsracl
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: tnsrACL is a definition of tnsr ALC that should be created.
        type: object
        required:
        - spec
        properties:
          spec:
            description: tnsrACL.spec represents the desired state for the ACL which is to be applied to tnsr.
              Contains the name of the ACL list, the interface it should apply to, and it's sequence number.
            type: object
            properties:
              name:
                type: string
              interface:
                type: string
              sequence:
                type: integer
            required:
            - name
            - interface
            - sequence
          status:
            type: object
            properties:
              present:
                type: boolean
              applied:
                type: boolean
              applied_acl_name:
                type: string
              applied_interface:
                type: string
              applied_sequence:
                type: integer
              error:
                type: string
