apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argo-notifications-testing-2
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo-notifications-testing-2
spec:
  project: akuity
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/akuity/guestbook
  destination:
    name: in-cluster
    namespace: guestbook