apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: akuity
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/akuity/guestbook
  destination:
    name: in-cluster
    namespace: guestbook