image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/home-operations/sonarr
  tag: 4.0.16.2943

env:
  TZ: America/Toronto

ingress:
  main:
    enabled: false

persistence:
  media:
    enabled: true
    type: nfs
    server: "192.168.1.10"
    path: /Media/Television
    mountPath: /media
  nzbget:
    enabled: true
    type: nfs
    server: "192.168.1.10"
    path: /Media/nzbget
    mountPath: /nzbget
  config:
    enabled: true
    storageClass: longhorn
    size: 100Gi

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
