alertmanager:
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchExpressions:
      - key: alertmanagerConfig
        operator: In
        values:
        - prom-stack
  ingress:
    enabled: true
    hosts:
      - alertmanager.akuity.burrell.tech
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16"
      external-dns.alpha.kubernetes.io/exclude: 'true'
    tls:
    - secretName: alertmanager.akuity.burrell.tech
      hosts:
      - alertmanager.akuity.burrell.tech


grafana:
  defaultDashboardsTimezone: America/Toronto
  ingress:
    enabled: true
    hosts:
      - grafana.akuity.burrell.tech
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: 'unproxied.burrell.tech'
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
    tls:
    - secretName: grafana.akuity.burrell.tech
      hosts:
      - grafana.akuity.burrell.tech


prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.akuity.burrell.tech
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16"
      external-dns.alpha.kubernetes.io/exclude: 'true'
    tls:
    - secretName: prometheus.akuity.burrell.tech
      hosts:
      - prometheus.akuity.burrell.tech
  additionalServiceMonitors:

  - name: argocd-metrics
    selector:
      matchLabels:
        app.kubernetes.io/name: argocd-metrics
    namespaceSelector:
      matchNames:
      - argocd
    endpoints:
    - port: metrics

  - name: argocd-server-metrics
    selector:
      matchLabels:
        app.kubernetes.io/name: argocd-server-metrics
    namespaceSelector:
      matchNames:
      - argocd
    endpoints:
    - port: metrics

  - name: argocd-repo-server-metrics
    selector:
      matchLabels:
        app.kubernetes.io/name: argocd-repo-server
    namespaceSelector:
      matchNames:
      - argocd
    endpoints:
    - port: metrics

  - name: argocd-applicationset-controller-metrics
    selector:
      matchLabels:
        app.kubernetes.io/name: argocd-applicationset-controller
    namespaceSelector:
      matchNames:
      - argocd
    endpoints:
    - port: metrics

  - name: clusterplex-metrics
    selector:
      matchLabels:
        app.kubernetes.io/name: clusterplex-orchestrator
    namespaceSelector:
      matchNames:
      - plex
    endpoints:
    - port: orchestrator
      path: /metrics
