alertmanager:
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
      - key: alertmanagerConfig
        operator: In
        values:
        - prom-stack
  # config:
  #   global:
  #     resolve_timeout: 5m
  #   inhibit_rules:
  #     - source_matchers:
  #         - 'severity = critical'
  #       target_matchers:
  #         - 'severity =~ warning|info'
  #       equal:
  #         - 'namespace'
  #         - 'alertname'
  #     - source_matchers:
  #         - 'severity = warning'
  #       target_matchers:
  #         - 'severity = info'
  #       equal:
  #         - 'namespace'
  #         - 'alertname'
  #     - source_matchers:
  #         - 'alertname = InfoInhibitor'
  #       target_matchers:
  #         - 'severity = info'
  #       equal:
  #         - 'namespace'
  #   route:
  #     group_by: ['alertname']
  #     group_wait: 10s
  #     group_interval: 10s
  #     repeat_interval: 30m
  #     receiver: 'email'
  #     routes:
  #     - receiver: 'null'
  #       matchers:
  #         - alertname =~ "InfoInhibitor|Watchdog"
  #   receivers:
  #   - name: 'null'
  #   - name: "email"
  #     email_configs:
  #     - to: "noah+alerting@burrell.tech"
  #       from: "no-reply@burrell.tech"
  #       smarthost: "smtp.smtp:25"
  #       require_tls: false
  #   templates:
  #   - '/etc/alertmanager/config/*.tmpl'
  ingress:
    enabled: true
    hosts:
      - alertmanager.akuity.burrell.tech
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16"
      external-dns.alpha.kubernetes.io/exclude: 'true'
    tls:
    - secretName: alertmanager.akuity.burrell.tech
      hosts:
      - alertmanager.akuity.burrell.tech

grafana:
  defaultDashboardsTimezone: America/Toronto
  ingress:
    enabled: true
    hosts:
      - grafana.akuity.burrell.tech
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: 'unproxied.burrell.tech'
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
    tls:
    - secretName: grafana.akuity.burrell.tech
      hosts:
      - grafana.akuity.burrell.tech

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.akuity.burrell.tech
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16"
      external-dns.alpha.kubernetes.io/exclude: 'true'
    tls:
    - secretName: prometheus.akuity.burrell.tech
      hosts:
      - prometheus.akuity.burrell.tech

  additionalServiceMonitors:
  - name: argocd-metrics
    selector:
      matchLabels:
        app.kubernetes.io/name: argocd-metrics
    namespaceSelector:
      matchNames:
      - argocd
    endpoints:
    - port: metrics

  - name: argocd-server-metrics
    selector:
      matchLabels:
        app.kubernetes.io/name: argocd-server-metrics
    namespaceSelector:
      matchNames:
      - argocd
    endpoints:
    - port: metrics

  - name: argocd-repo-server-metrics
    selector:
      matchLabels:
        app.kubernetes.io/name: argocd-repo-server
    namespaceSelector:
      matchNames:
      - argocd
    endpoints:
    - port: metrics

  - name: argocd-applicationset-controller-metrics
    selector:
      matchLabels:
        app.kubernetes.io/name: argocd-applicationset-controller
    namespaceSelector:
      matchNames:
      - argocd
    endpoints:
    - port: metrics
