alertmanager:
  config:
    receivers:
    - name: "null"
    - name: "email"
      emailConfigs:
      - to: "noah+alerting@burrell.tech"
        from: "noah@burrell.tech"
        smarthost: "smtp.gmail.com:587"
        authUsername: "noah@burrell.tech"
        authPassword:
          name: gmail-secret
          key: password
        authIdentity: "noah@burrell.tech"
  ingress:
    enabled: true
    hosts:
      - alertmanager.akuity.burrell.tech
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: 'unproxied.burrell.tech'
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
    tls:
    - secretName: alertmanager.akuity.burrell.tech
      hosts:
      - alertmanager.akuity.burrell.tech

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.akuity.burrell.tech
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: 'unproxied.burrell.tech'
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
    tls:
    - secretName: grafana.akuity.burrell.tech
      hosts:
      - grafana.akuity.burrell.tech

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.akuity.burrell.tech
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: 'unproxied.burrell.tech'
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
    tls:
    - secretName: prometheus.akuity.burrell.tech
      hosts:
      - prometheus.akuity.burrell.tech