apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - loadbalancer.yaml

namespace: ingress-nginx

patches:
  # Make Nginx the default ingress class
  - target:
      kind: IngressClass
      name: nginx
    patch: |-
      - op: add
        path: /metadata/annotations/ingressclass.kubernetes.io~1is-default-class
        value: "true"