image:
  pullPolicy: IfNotPresent

env:
  TZ: America/Toronto
  PGID: 0
  PUID: 0

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/target: 'burrell.tech'
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
    hosts:
      - host: ombi.burrell.tech
        paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: ombi.burrell.tech
      hosts:
      - ombi.burrell.tech

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 5Gi

