# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: chia-node
#   namespace: argocd
# spec:
#   project: external
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true
#   sources:
#   - repoURL: https://github.com/noahburrell0/k8s.git
#     targetRevision: main
#     path: configs/external/chia-node
#   destination:
#     name: in-cluster
#     namespace: chia-node

