apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chia-node
  namespace: argocd
  labels:
    app.kubernetes.io/instance: test
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/chia-node
  destination:
    server: https://kubernetes.default.svc
    namespace: chia-node

