apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/ghost
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/ghost/configs
  destination:
    server: https://kubernetes.default.svc
    namespace: ghost

