apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: ghost
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.1.58
    helm:
      valueFiles:
      - $values/configs/external/ghost/values.yaml
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/ghost/configs
  destination:
    name: in-cluster
    namespace: ghost

