apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.10.4
    helm:
      valueFiles:
      - $values/configs/external/harbor/values.yaml
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/harbor/configs
  destination:
    name: in-cluster
    namespace: harbor
  ignoreDifferences: # Ignore dynamic parameters that cause incorrect OutOfSync status
  - kind: Deployment
    group: apps
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1secret
    - /spec/template/metadata/annotations/checksum~1secret-core
    - /spec/template/metadata/annotations/checksum~1secret-jobservice
  - kind: Secret
    name: harbor-core
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - kind: Secret
    jsonPointers:
    - /data/CSRF_KEY
    - /data/secret
    - /data/JOBSERVICE_SECRET
    - /data/REGISTRY_HTTP_SECRET
