apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/harbor
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/harbor/configs
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

