apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invoice-ninja
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/invoiceninja
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/invoiceninja/configs
  destination:
    name: in-cluster
    namespace: invoice-ninja
  ignoreDifferences: # Ignore dynamic parameters that cause incorrect OutOfSync status
  - kind: Secret
    name: invoice-ninja-redis
    jsonPointers:
    - /data/redis-password
  - kind: StatefulSet
    group: apps
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1secret