apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-site
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/noahburrell0/k8s.git
    path: configs/external/main-site
    targetRevision: main
  destination:
    name: in-cluster
    namespace: main-site

