apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-1
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/minio
  destination:
    name: in-cluster
    namespace: minio-1

