apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: paperless
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 8.8.3
    helm:
      valueFiles:
      - $values/configs/external/paperless/values.yaml
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    ref: values
  destination:
    name: in-cluster
    namespace: paperless

