apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: plex
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 6.3.3
    helm:
      valueFiles:
      - $values/configs/external/plex/values.yaml
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: clusterplex
    ref: values
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: clusterplex
    path: configs/external/plex/clusterplex
  destination:
    name: in-cluster
    namespace: plex

