apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafile
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/seafile
  - repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/seafile/secrets
  destination:
    name: in-cluster
    namespace: seafile

