apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/noahburrell0/k8s.git
    targetRevision: main
    path: configs/external/wireguard
  destination:
    name: in-cluster
    namespace: wireguard

