apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: seafile
  releaseName: seafile
  namespace: seafile
  repo: seafile
  valuesFile: values.yaml

resources:
- configs/image-pull-secret.yaml
- configs/seafile-external-secret.yaml
- configs/gateway.yaml
- configs/redis.yaml