image:
  repository: seafileltd/seafile-pro-mc
  tag: 12.0.21

# imagePullSecrets:
#   - name: image-pull-secret

env:
  SEAFILE_ADMIN_EMAIL: noah@burrell.tech
  SEAFILE_SERVER_HOSTNAME: seafile.burrell.tech
  SEAFILE_SERVER_PROTOCOL: https
  FORCE_HTTPS_IN_CONF: "true"
  SEAFILE_ADMIN_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: seafile-external-secret
        key: SEAFILE_ADMIN_PASSWORD
  DB_ROOT_PASSWD:
    valueFrom:
      secretKeyRef:
        name: seafile-external-secret
        key: DB_ROOT_PASSWD
  JWT_PRIVATE_KEY:
    valueFrom:
      secretKeyRef:
        name: seafile-external-secret
        key: JWT_PRIVATE_KEY

ingress:
  main:
    enabled: false
  sso:
    enabled: false

persistence:
  shared:
    enabled: true
    nameOverride: longhorn-rwo
    type: pvc
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Ti

mariadb:
  image:
    repository: bitnamilegacy/mariadb
    tag: 10.7.8-debian-11-r6
  enabled: true
  architecture: standalone
  auth:
    database: seafile
    username: seafile
    existingSecret: seafile-external-secret
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 25Gi
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      slow_query_log=0
      slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
      long_query_time=10.0

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid