apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: smtp
    app.kubernetes.io/name: smtp
  name: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: smtp
      app.kubernetes.io/name: smtp
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: smtp
        app.kubernetes.io/name: smtp
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: smtp-secrets
          image: djjudas21/smtp-relay
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 60
            tcpSocket:
              port: smtp
          name: smtp
          ports:
            - containerPort: 25
              name: smtp
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 30
            tcpSocket:
              port: smtp
          resources:
            limits:
              cpu: 200m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 10Mi
          securityContext: {}
      securityContext: {}
      serviceAccountName: smtp