apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  ports:
    - name: smtp
      port: 25
      protocol: TCP
      targetPort: smtp
  selector:
    app.kubernetes.io/instance: smtp
    app.kubernetes.io/name: smtp
  type: ClusterIP