apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secrets
spec:
  target:
    name: my-example-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .user }}
        password: |-
          {{ .user }}
        testKey: |-
          {{ .testKey }}
  data:
    - secretKey: user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cd55f0d4-d314-4e9e-8041-b034014421e1
        property: username
    - secretKey: pass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cd55f0d4-d314-4e9e-8041-b034014421e1
        property: password
    # Example with a custom Field in the bitwarden vault item
    - secretKey: testKey
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cd55f0d4-d314-4e9e-8041-b034014421e1
        property: testKey
