adguard-home:

  image:
    repository: adguard/adguardhome
    tag: v0.107.26
    pullPolicy: IfNotPresent

  persistence:
    config:
      enabled: true
      mountPath: /opt/adguardhome/conf
      storageClass: nfs-rwo
      size: 1Gi

  service:
    main:
      primary: true
      ports:
        http:
          port: 3000
    dns-tcp:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: bgp-pool
        metallb.universe.tf/allow-shared-ip: "adguard"
      loadBalancerIP: 172.19.0.11
      ports:
        dns-tcp:
          enabled: true
          port: 53
          protocol: TCP
          targetPort: 53
      externalTrafficPolicy: Local
    dns-udp:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: bgp-pool
        metallb.universe.tf/allow-shared-ip: "adguard"
      loadBalancerIP: 172.19.0.11
      ports:
        dns-udp:
          enabled: true
          port: 53
          protocol: UDP
          targetPort: 53
      externalTrafficPolicy: Local

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 1024m
        external-dns.alpha.kubernetes.io/exclude: 'true'
      hosts:
        - host: adguard.home.burrell.tech
          paths:
          - path: /
            pathType: Prefix
      tls:
      - secretName: adguard.home.burrell.tech
        hosts:
        - adguard.home.burrell.tech
