externalURL: https://registry.burrell.tech

expose:
  type: clusterIP
  tls:
    enabled: false

trivy:
  enabled: false
notary:
  enabled: false

persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: registry
    chartmuseum:
      existingClaim: chartmuseum
    jobservice:
      jobLog:
        existingClaim: jobservice
    database:
      existingClaim: database
    redis:
      existingClaim: redis

updateStrategy:
  type: Recreate

existingSecretSecretKey: harbor-secrets
existingSecretAdminPasswordKey: harbor-secrets

registry:
  credentials:
    username: root
    existingSecret: harbor-secrets
