externalURL: https://registry.burrell.tech

expose:
  type: ingress
  ingress:
    hosts:
      core: registry.burrell.tech
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: 'burrell.tech'
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
  tls:
    certSource: secret
    secret:
      secretName: registry.burrell.tech-tls

trivy:
  enabled: false
notary:
  enabled: false

persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: registry
    chartmuseum:
      existingClaim: chartmuseum
    jobservice:
      jobLog:
        existingClaim: jobservice
    database:
      existingClaim: database
    redis:
      existingClaim: redis

updateStrategy:
  type: Recreate

existingSecretSecretKey: harbor-sealed-secrets
existingSecretAdminPasswordKey: harbor-sealed-secrets

registry:
  credentials:
    username: root
    existingSecret: harbor-sealed-secrets
