apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-notifications-secret
spec:
  encryptedData:
    #SLACK-TOKEN: AgBsqcz+kqymw6DDvrwOv9m8qZBjrNAzsHUbWMcv0CZL7mDuWZGKO1juo9gKLvRUg9zwDmNGG3zKrM2qJpwYlSDYT19X8xLIbVFzq8Ims2VN6JmD7fSuhNPvRfDrQ4NnWpcZcrEsddrkqK8oxZtoRn/h/C9WSayqGMyMJEVuPL8VTeDWy08z4GFXQ+JnlSF1VNkA4oK2RlFeN6suMLyVFrPeNT2j+wGTgg9LIWQXGww+JywYBVanyzuhVOa0n9qYpVBxMdJKEb5I33VvbHtEIVJLjZWysAWq2iSKitDmP+Mc+D0d+QNKi1jVPdbJkiv9DbOL7KDfcGd/B7eqIi5J5JCDCQEga2C8w8bUx0aMkYmArlEji9UDeeXXyA5W/bO4jUm9+ggJPo2Zj1FLWtz7uKG+t37ocfW+hf0kGWCJjpqZ0PJ4SP7VlJXNP87ogPVqk/0Ku59lzWLMulvaKNB0QXdB6ZNK+Wu1gpc40aN65spcr2UrMYI7YfgWI3+QeL3gPiSV4aeTTio5oyjlwi032FLLMYyuyVQaz3r2EkUYmnNZ9BpC0bvlRX4KCeeDkooCcETVqMB/jb83hsvSuhWdKtK17OIJCPE8gPoGZspIXyZijxzNtluQ0T/glyAd4PfqPX/wILwuWVnnztNKCW9brUxA/eddPLWf27da46u0RFeB2iBeY9jaCdawAD32F2XqgJ3fP2CPsbgIpLAi+GJku/4CizSoI09Z94thlZRapS9vkB4F4ANuTZRzY5zZ+suDq9VxE/Oe1VEFodI=
    SLACK-TOKEN: AgAmbtjaJC/RGcyvBRMla0tk5L022BYHQ2AU2VaAKB8i21JWsLXYCZQ65Ex6H4kSpXTVbSJFdfBpIFduRInnX+Qko4s+Zmi7UfAaukTp/XYE6GclB4O7O36dsJF5ZHdwe9jAcDmp7Mp+HQeUiaNu9nzVwiYco3vEDUhqf3B0YzpeR1cwzTc9K8cs11SQA0oJw1bHFG25peDU+50VhyJteWnyICo0ozmqWcAdlNa0I2tf0o6hjh5zfuTPCXcKecLKpj2GDPUnJTb2FVsotxFBUQLwymzQeHf1jJvF3pbgo1aruTkzzRgYia5DdBcuLSI9eiWEUsMMRX/PC+feoNz0tDSpDWzZlYo6N81eCOfps0BEK5UUCheV1sQl0kO9y7Fylds6t+HYQ6sTrWnIfLYpPeUS1fWyZN55KegdGjZlqmCf2AYu0E5K73bD0eD/Jp7s6apXqgxuhBz7e+nVNo7SeFqg7MQWYz17hVlkx4U/kv+a+xJXNz+4WyhWtTOnYnjvBTz7Up3hcf+WnuJX3nDc9MmRSTpgsKiLs7oQfPVYtAUV1obUqC1EhtP1TbhdfhNq5fSpc88On4mvBIy1THwT3E5Qx/cTzjx2mAlSY6nNbjvl/dKn+af4bG8h45SXQ+2LFw3eKWLnPP5tNIA7fcHcw097v9//Qi1f7Su2WBZMP0+1RQDC+Mv/OqNdh8KKUyv9GcQ=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: argocd-notifications-secret
      namespace: argocd
