# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   annotations:
#     sealedsecrets.bitnami.com/cluster-wide: "true"
#   name: argocd-notifications-secret
# spec:
#   encryptedData:
#     #SLACK-TOKEN: AgBsqcz+kqymw6DDvrwOv9m8qZBjrNAzsHUbWMcv0CZL7mDuWZGKO1juo9gKLvRUg9zwDmNGG3zKrM2qJpwYlSDYT19X8xLIbVFzq8Ims2VN6JmD7fSuhNPvRfDrQ4NnWpcZcrEsddrkqK8oxZtoRn/h/C9WSayqGMyMJEVuPL8VTeDWy08z4GFXQ+JnlSF1VNkA4oK2RlFeN6suMLyVFrPeNT2j+wGTgg9LIWQXGww+JywYBVanyzuhVOa0n9qYpVBxMdJKEb5I33VvbHtEIVJLjZWysAWq2iSKitDmP+Mc+D0d+QNKi1jVPdbJkiv9DbOL7KDfcGd/B7eqIi5J5JCDCQEga2C8w8bUx0aMkYmArlEji9UDeeXXyA5W/bO4jUm9+ggJPo2Zj1FLWtz7uKG+t37ocfW+hf0kGWCJjpqZ0PJ4SP7VlJXNP87ogPVqk/0Ku59lzWLMulvaKNB0QXdB6ZNK+Wu1gpc40aN65spcr2UrMYI7YfgWI3+QeL3gPiSV4aeTTio5oyjlwi032FLLMYyuyVQaz3r2EkUYmnNZ9BpC0bvlRX4KCeeDkooCcETVqMB/jb83hsvSuhWdKtK17OIJCPE8gPoGZspIXyZijxzNtluQ0T/glyAd4PfqPX/wILwuWVnnztNKCW9brUxA/eddPLWf27da46u0RFeB2iBeY9jaCdawAD32F2XqgJ3fP2CPsbgIpLAi+GJku/4CizSoI09Z94thlZRapS9vkB4F4ANuTZRzY5zZ+suDq9VxE/Oe1VEFodI=
#     SLACK-TOKEN: AgCgU0m97z7Cjl29B5AkkUcZUwngGVVUNWpc03yWuHxkACB/apweCO0aXoOBAweH9UvNfj1IMKeMgVtqKBET24uBYdSzjMUD9isE3HLWSQNKRP5kwHs0mIRuRfBTJgnae/+Lr2tUewWf2SuX5t1vcWL6TpzqsFNB1IA4l8sG0Smw6AFu5dZ/riBMYalW9jdnOrma3hjFfD4gwXDu1evEKDpvISaZ5gVxlqVWYiuICu76aoODNJjGgVoQ2Amn8VBYjzWLF3RCcMuxSd1Z8+EGl/CXrBJJL0exC5SKBpa92yoirEpjfGNm8TfegThOJHTNtkyb1qSNKg8voysBrBlAKwRl5LSMNK9pyiU7/mchVuqZVnojUBxq0ndC4KA2mN+2czhKOaAwmZrGLQriOR3DeaZkHYg/ulFBybblOGPrSsenhYDsgIfMM3GVgL+9dKpZmPV7Jg9JjOyciEPMr/ac2TiHRa/3pSV9TvAwTBVFzkm3+qoo2w3Oa/kJWkFBKAUBBCEY94oBq0wo4qR+zZJb1BzNuswcah5pBCLWjKH6i0M/+6zEeQNnDyksjhxPNtgENTrJbDoGPrJDNNiIhem0RDWmgrEC35kv047K+32q/2ZyMcNKWRGuNNl1ReU8MQGgBIF5OwnYmcH6mPArZKH+6G5WYvHTf4uN02x8MbAQmV2b6mw9y6qC5+k9dCOuyYJSgbbqQLF7ZdZEtolKRoHa/AxKaS8+8sI9B0oDueJNpAIP3A+HbvEiC2aB2+2BTYQbUb3dHaK2ZFejMDA=
#   template:
#     data: null
#     metadata:
#       annotations:
#         sealedsecrets.bitnami.com/cluster-wide: "true"
#       name: argocd-notifications-secret
#       namespace: argocd
