apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-ldap-secret
spec:
  encryptedData:
    dex.ldap.bindDN: AgBeQSBIb4WFest3MWoMJMouISpi437Nhxthnx3dfdj4702haiQ8yAT/KH46LKB1t4wQ4EedPqq60uSvasfWnXTW6wkeymQYecei4nuIatYzytA7Xv3y84ab0UF2/L2uXsk+OGfFkC78VSpGfwGCghuaeFAJYA66BLBvyzVeEFeNzVY6vRi/3gOo+nL3eAzYRXgXToi2DzU0D57M7181WhLcJVJwFbZo5FlCekd6/jlI2XG+bwOpIlOgzA7TNaOl+DMixpDx9V5ak0pjPGNbwNgRgOvbp3Dq6syF9FkpXL/nN9hvB1lyWQyYcfvD9BpHw7St1b9jsR2QO2LXkFWqUrBjp0tqUOPKVmyYIAJxLTOcdHTYeitGxLKTJXRCM/LMN0YBaT548G+ARC6FUbzuPo+Yoz1Wc+0OvbA+9ai9stq3ylRSz9S0+7S2ofPhdXy/XOQWigWk/FhQ/oLTmbK6CJash5wuDcIIsv23RBPlCjJn7pDfAjnBc3RFw0w+cSUonuSNvd/Yd5i65upBQxoKWJ8Gd3bvZ94xHh/9z6v/tYmDkA5K66C33OhmsclzZd4cl5ozr3HlClDx3dgf9coDzYVP42IrQNkP7Uq5LLFu4Xv6pHPy7VBwjpuiOhRrOORfVept4hb+GpOwpO/FeVjkYziQc2PlOSUVvSX16fyZH9AdeJ01XQytE/pnCEgDviGqv/4fQgujZLeZ4gfHp/EcImNnXLo2z7JWWmc1rnArsfpIh9G4ygA3bi0W/21MzQ==
    dex.ldap.bindPW: AgCnASILUfxSkpJRlO85fBRw+L/RMTAO6hRh4AHE5zD+g8d0JUSb/Oa2LhQpgxEovFpiyzzCZaXt4u/dNplIlFr3kJqyrlrVovkEWzHs36Yv1WcHS3Q/B8JCOZfnV3Ta6oYEmxY4C+zGDMuWpYphq32VPuIC4gi0YNSUKcfxsI/59VIitvNO7BiZOk79M0u9iBxkgLqScg56mPV5N1Mh68I4ig95LkLFOdeucfmnzh6EE7/pxBUv8W/Bv1OC9B2ri/IA1S6QazBvp4ZCH3zmHr7BkolmdbJfEYeq2HFqeNF0ajCw9Jw9djkf6du8Ub2qR7FEMVTRlomYjaNd8sqCxsKMmlWmguMCV42hJhritPGnDDiT+LvRaRXU1XQ6vePSalz37dDcLzXbjacc//nvcxWA9CEIFNt/TbaOI6u8KL2iIZ7pG4d6e2uzubqYRp5kzXCyS5gQf77R8xVDjWuEk5uaPEUZsYNb2iclNTzZ0WWyKeiJbzmmB8+BQT22bD0i4QYbXxSXCFWnW5HW913bcIH/hmpBP0oRz007Y1MphLE1U1SLuyvwQtH9bEaCFNeB1/YLJZOMxscIrf4FYoEM5/7/v0q1Byn6FQLJlhdyW5ITsG4hIQxvFykXVbszY6ELmTecfaFIPhyu9MGaaUI55nVGpv3L/F1TD7AyEwv4L7oYlnXqf/rPXWj/9z1Hsw2UBD3QU/e3nhoI0M96Ivwp0A==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-ldap-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-ldap-secret
      namespace: argocd
    type: Opaque