apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-ldap-secret
spec:
  encryptedData:
    dex.ldap.bindDN: AgCQZF6igAMaEiswYkR5BJG8eiAVZeC+ombut7KpGez4AR/ZT0ADMOmlEOzUshd1k7UvQ6m9EQGNLJ2Bimfmhb9MQS8E7r3IUazbbZT/8r7q6GoLT7f7HjCQbM1rjgRsQ+yysHEKeEN9oph/6+Xtbkp61qSYRF+i48AbYnSwwNH4aaSaNzlrFe90k8rmkhZnXUyVZmsNlgOt6+z/C0CSVRY7kxhN070w04BqiEmPqXpeQD1tp7VrQX+2evHN+iL5d+28566beic3fbqikdcI9Qwjfcf0q8b38SU7z3CE6lWtmA6hHe7Ls8J8KPo67OmZit8OxFMUZ7apzdhUVzVebZTmTeqbjjpgV8fEO5MbMewG/RWdnjwe7v5SCTLLe1ct8RjUXc7HkULjDC4aD6fQs05G9Pk35GgJeE7obvLpmpZAi+yC+LWMlD7r9/Sc1c94yY3SkAQ9iZ4A9X2yRnLsnWCBiRdV2SK23GppjMKSN45r8SRQOO1+aIRC69JxcROMp6LyZTwxxISU0CXsy0RBpxXyKn7r1Rb076onrTTS/RLp7smBN9ERZNi5S0TY9DRe2ZAneX1hYLz6dABSaK/OZ06zA+3gebbUiph6HtiEzAKL6VZn1kXcA2RmMnk1LY1bAnFIaOnaEXBhWZgssbWVkrygDJoupJHUxSFGziVvvH56qGlhJTv0lEoDlx+XFEq6mlJ7IctCj0PXf+T3W7omprqQJynOb2zyCF+7LH7Ss9/ei57vBA==
    dex.ldap.bindPW: AgCnASILUfxSkpJRlO85fBRw+L/RMTAO6hRh4AHE5zD+g8d0JUSb/Oa2LhQpgxEovFpiyzzCZaXt4u/dNplIlFr3kJqyrlrVovkEWzHs36Yv1WcHS3Q/B8JCOZfnV3Ta6oYEmxY4C+zGDMuWpYphq32VPuIC4gi0YNSUKcfxsI/59VIitvNO7BiZOk79M0u9iBxkgLqScg56mPV5N1Mh68I4ig95LkLFOdeucfmnzh6EE7/pxBUv8W/Bv1OC9B2ri/IA1S6QazBvp4ZCH3zmHr7BkolmdbJfEYeq2HFqeNF0ajCw9Jw9djkf6du8Ub2qR7FEMVTRlomYjaNd8sqCxsKMmlWmguMCV42hJhritPGnDDiT+LvRaRXU1XQ6vePSalz37dDcLzXbjacc//nvcxWA9CEIFNt/TbaOI6u8KL2iIZ7pG4d6e2uzubqYRp5kzXCyS5gQf77R8xVDjWuEk5uaPEUZsYNb2iclNTzZ0WWyKeiJbzmmB8+BQT22bD0i4QYbXxSXCFWnW5HW913bcIH/hmpBP0oRz007Y1MphLE1U1SLuyvwQtH9bEaCFNeB1/YLJZOMxscIrf4FYoEM5/7/v0q1Byn6FQLJlhdyW5ITsG4hIQxvFykXVbszY6ELmTecfaFIPhyu9MGaaUI55nVGpv3L/F1TD7AyEwv4L7oYlnXqf/rPXWj/9z1Hsw2UBD3QU/e3nhoI0M96Ivwp0A==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-ldap-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-ldap-secret
      namespace: argocd
    type: Opaque