apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-update-patch
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - update
  - patch
- apiGroups:
  - "apps"
  resources:
  - "*"
  verbs:
  - update
  - patch