apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
  - argocd-install.yaml

resources:
  - argocd-ingress.yaml
  - argocd-external-ingress.yaml
  - argocd-ldap-secret.yaml
  - argocd-notifications-secret.yaml
  - clusterrole-argocd-update-patch.yaml
  - github-credentials.yaml

namespace: argocd

patches:
  # Add pod exec functionality to CR to enable websocket terminal in ArgoCD
  - target:
      kind: ClusterRole
      name: argocd-server
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - create
  - target:
      kind: Deployment
      name: argocd-redis-ha-haproxy
    patch: |-
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
  - target:
      kind: StatefulSet
      name: argocd-redis-ha-server
    patch: |-
      - op: replace
        path: /spec/template/spec/affinity
        value: {}
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/affinity
        value: {}
