apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth0-config
spec:
  target:
    name: auth0-config
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: "{{ .auth0config }}""
  data:
    - secretKey: auth0config
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1ebc2b5c-7405-441d-91f8-b4170016b2d3
        property: auth0config