apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: frigate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
