apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-s3-credentials
spec:
  target:
    name: frigate-s3-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        S3_ACCESS_KEY_ID: |-
          {{ .s3AccessKeyId }}
        S3_SECRET_ACCESS_KEY: |-
          {{ .s3SecretAccessKey }}
        S3_BUCKET: |-
          {{ .s3Bucket }}
        S3_REGION: |-
          {{ .s3Region }}
        S3_ENDPOINT: |-
          {{ .s3Endpoint }}
  data:
    - secretKey: s3AccessKeyId
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 986438a5-2694-4c45-a49c-b42500118b20
        property: username
    - secretKey: s3SecretAccessKey
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 986438a5-2694-4c45-a49c-b42500118b20
        property: password
    - secretKey: s3Bucket
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 986438a5-2694-4c45-a49c-b42500118b20
        property: bucket
    - secretKey: s3Region
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 986438a5-2694-4c45-a49c-b42500118b20
        property: region
    - secretKey: s3Endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 986438a5-2694-4c45-a49c-b42500118b20
        property: endpoint
